sudo: required
services:
  - docker

before_install:
  - docker build -t arielmagbanua/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run arielmagbanua/react-test npm test -- --coverage

after_success:
  - docker build -t arielmagbanua/multi-client ./client
  - docker build -t arielmagbanua/multi-nginx ./nginx
  - docker build -t arielmagbanua/multi-server ./server
  - docker build -t arielmagbanua/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push arielmagbanua/multi-client
  - docker push arielmagbanua/multi-nginx
  - docker push arielmagbanua/multi-server
  - docker push arielmagbanua/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-759772833449
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_ACCESS_KEY'